# Github workflow

name: CI

# Triggers the workflow on push or pull request events only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      # FTP upload
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.OPENJOBPOSTING_FTP_SERVER }}/var/www/vhosts/openjobposting.com/httpdocs/www.openjobposting.com/
          ftp-username: ${{ secrets.OPENJOBPOSTING_FTP_USERNAME }}
          ftp-password: ${{ secrets.OPENJOBPOSTING_FTP_PASSWORD }}
          git-ftp-args: --insecure

      # SSH connect
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OPENJOBPOSTING_SSH_HOST }}
          username: ${{ secrets.OPENJOBPOSTING_SSH_USERNAME }}
          password: ${{ secrets.OPENJOBPOSTING_SSH_PASSWORD }}
          port: ${{ secrets.OPENJOBPOSTING_SSH_PORT }}
          script: |
            cd /var/www/vhosts/openjobposting.com/httpdocs/www.openjobposting.com/
            ${{ secrets.OPENJOBPOSTING_PHP }} ${{ secrets.OPENJOBPOSTING_COMPOSER }} install
            ${{ secrets.OPENJOBPOSTING_PHP }} artisan migrate --force
